name: CDK Stack Unit Tests
on:
    workflow_dispatch:
    push:
        branches:
            - '*'
        paths:
            - 'cdk/**'
            - 'bin/**'
            - 'tests/**/*.test.ts'
    pull_request:
        branches:
            - '*'
        paths:
            - 'cdk/**'
            - 'bin/**'
            - 'tests/**/*.test.ts'
jobs:
    cdk-unit-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
            - name: Install dependencies
              run: npm ci
            - name: Run unit tests
              run: npm run test