name: CDK Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true
        type: string
      environment:
        description: 'Deployment environment'
        required: true
        type: choice
        default: 'dev'
        options:
        - dev
        - staging
        - production
env:
  MY_ENV_NAME: "my-env-name"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
      
      - name: Conigure AWS credentials choice Environment
        if: ${{ github.event.inputs.environment == 'dev' }}
        run: |
          echo "envroments is dev"
          echo "MY_ENV_NAME=development" >> $GITHUB_ENV
      - name: Conigure AWS credentials choice Environment
        if: ${{ github.event.inputs.environment == 'staging' }}
        run: |
          echo "envroments is staging"
          echo "MY_ENV_NAME=staging" >> $GITHUB_ENV
      - name: display MY_ENV_NAME
        run: |
          echo ${{env.MY_ENV_NAME}}

    #   - name: Configure AWS credentials
    #     uses: aws-actions/configure-aws-credentials@v4
    #     with:
    #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       aws-region: ${{ secrets.AWS_REGION }}
    #   - name: Deploy with CDK
    #     run: |
    #       git checkout v${{ github.event.inputs.version }}
    #       npm run cdk deploy -- --all --require-approval never --context environment=${{ github.event.inputs.environment }}
      - name: Deploy with CDK
        run: |
            git checkout v${{ github.event.inputs.version }}
            # jq でpackage.jsonを表示
            cat package.json | jq