name: python ci
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Set up Python
        run: uv python install
      - name: Install the project
        run: uv sync --all-extras --dev
      - name : Run linters
        run: uvx ruff check
      - name: Run tests
        run: uv run pytest
