name: Preparation for Release(Versions and Release Notes)
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version'
        required: true
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  update-version-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Update root package.json version
        id: update-root-version
        run: |
          npm version ${{ github.event.inputs.version }} -m "Bump root version to %s"
          echo "new_version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Update app package.json version
        run: |
          cd app
          npm version ${{ steps.update-root-version.outputs.new_version }} -m "Bump app version to %s"
          cd ..

      - name: Commit app package.json changes
        run: |
          git add app/package.json
          git commit -m "Update app package.json to version ${{ steps.update-root-version.outputs.new_version }}"

      - name: Push changes
        run: |
          git push

      - name: Generate Release Notes
        id: release-notes
        run: |
          previous_tag=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || git rev-list --max-parents=0 HEAD)
          echo "Release Notes for v${{ steps.update-root-version.outputs.new_version }}:" > RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          git log ${previous_tag}..HEAD --pretty=format:"- %s" >> RELEASE_NOTES.md

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.update-root-version.outputs.new_version }}
          name: Release v${{ steps.update-root-version.outputs.new_version }}
          body_path: RELEASE_NOTES.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}